version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=admin_n8n
      - POSTGRES_PASSWORD=n8n1234
      - POSTGRES_DB=db_n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n:1.85.4
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=db_n8n
      - DB_POSTGRESDB_USER=admin_n8n
      - DB_POSTGRESDB_PASSWORD=n8n1234
      - GENERIC_TIMEZONE=America/Sao_Paulo
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./custom_nodes:/home/node/.n8n/custom
    depends_on:
      - postgres

volumes:
  postgres_data:
  n8n_data:
